/**
 * Plantilla de catálogo de demostración FarmaFácil.
 * Se COPIA a pharmacy_products de la farmacia (sin vínculo vivo a la plantilla).
 */

export const DEMO_CATALOG_VERSION = 'farmafacil_demo_v1';

export type DemoCatalogProduct = {
  sku: string;
  name: string;
  brand: string;
  category: string;
  description: string;
  price: number;
  stock: number;
  minStock: number;
};

export function demoSourceRef(sku: string): string {
  return `${DEMO_CATALOG_VERSION}:${sku}`;
}

/** ~30 productos genéricos de parafarmacia. Sin medicamentos con receta. Sin EAN reales. */
export const DEMO_CATALOG_PRODUCTS: DemoCatalogProduct[] = [
  // Higiene
  {
    sku: 'DEMO-001',
    name: 'Gel de baño piel sensible 500 ml',
    brand: 'FarmaDemo',
    category: 'Higiene',
    description: 'Producto de demostración. Gel de higiene diaria.',
    price: 4.95,
    stock: 24,
    minStock: 5,
  },
  {
    sku: 'DEMO-002',
    name: 'Jabón de manos dosificador 300 ml',
    brand: 'FarmaDemo',
    category: 'Higiene',
    description: 'Producto de demostración.',
    price: 3.5,
    stock: 30,
    minStock: 6,
  },
  {
    sku: 'DEMO-003',
    name: 'Toallitas húmedas higiene 60 uds',
    brand: 'FarmaDemo',
    category: 'Higiene',
    description: 'Producto de demostración.',
    price: 2.75,
    stock: 40,
    minStock: 8,
  },
  {
    sku: 'DEMO-004',
    name: 'Desodorante roll-on sin alcohol 50 ml',
    brand: 'FarmaDemo',
    category: 'Higiene',
    description: 'Producto de demostración.',
    price: 3.95,
    stock: 20,
    minStock: 4,
  },
  // Dermocosmética
  {
    sku: 'DEMO-005',
    name: 'Crema hidratante facial 50 ml',
    brand: 'FarmaDemo',
    category: 'Dermocosmética',
    description: 'Producto de demostración.',
    price: 12.9,
    stock: 18,
    minStock: 4,
  },
  {
    sku: 'DEMO-006',
    name: 'Sérum hidratante ligero 30 ml',
    brand: 'FarmaDemo',
    category: 'Dermocosmética',
    description: 'Producto de demostración.',
    price: 16.5,
    stock: 12,
    minStock: 3,
  },
  {
    sku: 'DEMO-007',
    name: 'Leche corporal hidratante 400 ml',
    brand: 'FarmaDemo',
    category: 'Dermocosmética',
    description: 'Producto de demostración.',
    price: 8.75,
    stock: 22,
    minStock: 5,
  },
  {
    sku: 'DEMO-008',
    name: 'Contorno de ojos hidratante 15 ml',
    brand: 'FarmaDemo',
    category: 'Dermocosmética',
    description: 'Producto de demostración.',
    price: 14.2,
    stock: 10,
    minStock: 2,
  },
  {
    sku: 'DEMO-009',
    name: 'Limpiador facial suave 200 ml',
    brand: 'FarmaDemo',
    category: 'Dermocosmética',
    description: 'Producto de demostración.',
    price: 9.9,
    stock: 16,
    minStock: 4,
  },
  // Infantil
  {
    sku: 'DEMO-010',
    name: 'Crema pañal protectora 100 ml',
    brand: 'FarmaDemo Baby',
    category: 'Infantil',
    description: 'Producto de demostración.',
    price: 6.5,
    stock: 25,
    minStock: 5,
  },
  {
    sku: 'DEMO-011',
    name: 'Gel higiene infantil 500 ml',
    brand: 'FarmaDemo Baby',
    category: 'Infantil',
    description: 'Producto de demostración.',
    price: 5.25,
    stock: 20,
    minStock: 4,
  },
  {
    sku: 'DEMO-012',
    name: 'Toallitas bebé sin perfume 80 uds',
    brand: 'FarmaDemo Baby',
    category: 'Infantil',
    description: 'Producto de demostración.',
    price: 3.2,
    stock: 35,
    minStock: 8,
  },
  {
    sku: 'DEMO-013',
    name: 'Champú suave infantil 250 ml',
    brand: 'FarmaDemo Baby',
    category: 'Infantil',
    description: 'Producto de demostración.',
    price: 4.8,
    stock: 18,
    minStock: 4,
  },
  // Bucodental
  {
    sku: 'DEMO-014',
    name: 'Pasta dental protección diaria 75 ml',
    brand: 'FarmaDemo',
    category: 'Bucodental',
    description: 'Producto de demostración.',
    price: 2.95,
    stock: 40,
    minStock: 10,
  },
  {
    sku: 'DEMO-015',
    name: 'Enjuague bucal diario 500 ml',
    brand: 'FarmaDemo',
    category: 'Bucodental',
    description: 'Producto de demostración.',
    price: 4.5,
    stock: 22,
    minStock: 5,
  },
  {
    sku: 'DEMO-016',
    name: 'Cepillo dental medio 1 ud',
    brand: 'FarmaDemo',
    category: 'Bucodental',
    description: 'Producto de demostración.',
    price: 2.4,
    stock: 50,
    minStock: 12,
  },
  {
    sku: 'DEMO-017',
    name: 'Hilo dental encerado 50 m',
    brand: 'FarmaDemo',
    category: 'Bucodental',
    description: 'Producto de demostración.',
    price: 3.1,
    stock: 28,
    minStock: 6,
  },
  // Solar
  {
    sku: 'DEMO-018',
    name: 'Protector solar facial SPF50 50 ml',
    brand: 'FarmaDemo Sun',
    category: 'Solar',
    description: 'Producto de demostración.',
    price: 15.9,
    stock: 14,
    minStock: 3,
  },
  {
    sku: 'DEMO-019',
    name: 'Protector solar corporal SPF30 200 ml',
    brand: 'FarmaDemo Sun',
    category: 'Solar',
    description: 'Producto de demostración.',
    price: 12.5,
    stock: 16,
    minStock: 4,
  },
  {
    sku: 'DEMO-020',
    name: 'Aftersun hidratante 200 ml',
    brand: 'FarmaDemo Sun',
    category: 'Solar',
    description: 'Producto de demostración.',
    price: 7.9,
    stock: 18,
    minStock: 4,
  },
  {
    sku: 'DEMO-021',
    name: 'Stick solar labial SPF30',
    brand: 'FarmaDemo Sun',
    category: 'Solar',
    description: 'Producto de demostración.',
    price: 5.5,
    stock: 20,
    minStock: 5,
  },
  // Cuidado capilar
  {
    sku: 'DEMO-022',
    name: 'Champú uso frecuente 400 ml',
    brand: 'FarmaDemo',
    category: 'Cuidado capilar',
    description: 'Producto de demostración.',
    price: 5.9,
    stock: 24,
    minStock: 5,
  },
  {
    sku: 'DEMO-023',
    name: 'Acondicionador hidratante 250 ml',
    brand: 'FarmaDemo',
    category: 'Cuidado capilar',
    description: 'Producto de demostración.',
    price: 6.4,
    stock: 18,
    minStock: 4,
  },
  {
    sku: 'DEMO-024',
    name: 'Mascarilla capilar nutritiva 200 ml',
    brand: 'FarmaDemo',
    category: 'Cuidado capilar',
    description: 'Producto de demostración.',
    price: 8.2,
    stock: 12,
    minStock: 3,
  },
  {
    sku: 'DEMO-025',
    name: 'Champú anticaspa suave 250 ml',
    brand: 'FarmaDemo',
    category: 'Cuidado capilar',
    description: 'Producto de demostración.',
    price: 7.1,
    stock: 15,
    minStock: 3,
  },
  // Ortopedia ligera
  {
    sku: 'DEMO-026',
    name: 'Muñequera elástica talla M',
    brand: 'FarmaDemo Care',
    category: 'Ortopedia ligera',
    description: 'Producto de demostración.',
    price: 9.5,
    stock: 10,
    minStock: 2,
  },
  {
    sku: 'DEMO-027',
    name: 'Tobillera elástica talla L',
    brand: 'FarmaDemo Care',
    category: 'Ortopedia ligera',
    description: 'Producto de demostración.',
    price: 11.2,
    stock: 8,
    minStock: 2,
  },
  {
    sku: 'DEMO-028',
    name: 'Rodillera elástica talla M',
    brand: 'FarmaDemo Care',
    category: 'Ortopedia ligera',
    description: 'Producto de demostración.',
    price: 13.9,
    stock: 8,
    minStock: 2,
  },
  {
    sku: 'DEMO-029',
    name: 'Faja lumbar de apoyo talla L',
    brand: 'FarmaDemo Care',
    category: 'Ortopedia ligera',
    description: 'Producto de demostración.',
    price: 18.5,
    stock: 6,
    minStock: 1,
  },
  {
    sku: 'DEMO-030',
    name: 'Taloneras de silicona 1 par',
    brand: 'FarmaDemo Care',
    category: 'Ortopedia ligera',
    description: 'Producto de demostración.',
    price: 7.75,
    stock: 14,
    minStock: 3,
  },
];
