import type {
  ActivityItem,
  Client,
  KpiPoint,
  Order,
  Pharmacy,
  PharmacyActivityItem,
  PharmacyUser,
  Product,
} from './types';

export const kpis: KpiPoint[] = [
  {
    label: 'Farmacias activas',
    value: '128',
    delta: 4.2,
    trend: [80, 84, 86, 90, 95, 102, 110, 118, 122, 128],
    icon: 'pharmacy',
  },
  {
    label: 'Clientes',
    value: '48.920',
    delta: 6.8,
    trend: [30, 32, 35, 38, 41, 43, 45, 46, 47, 48.9],
    icon: 'clients',
  },
  {
    label: 'Pedidos',
    value: '12.430',
    delta: 2.1,
    trend: [8, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.2, 12.4],
    icon: 'orders',
  },
  {
    label: 'Facturación mensual',
    value: '€ 184.320',
    delta: 9.4,
    trend: [120, 130, 138, 145, 150, 158, 165, 172, 178, 184],
    icon: 'revenue',
  },
  {
    label: 'Pedidos hoy',
    value: '342',
    delta: -1.2,
    trend: [40, 55, 60, 58, 62, 70, 80, 120, 240, 342],
    icon: 'today',
  },
  {
    label: 'Productos',
    value: '8.640',
    delta: 3.5,
    trend: [7.2, 7.4, 7.6, 7.8, 8, 8.1, 8.3, 8.4, 8.5, 8.6],
    icon: 'products',
  },
];

export const salesChart = [
  { month: 'Ene', ventas: 142, pedidos: 9.2 },
  { month: 'Feb', ventas: 158, pedidos: 10.1 },
  { month: 'Mar', ventas: 149, pedidos: 9.8 },
  { month: 'Abr', ventas: 171, pedidos: 11.4 },
  { month: 'May', ventas: 168, pedidos: 11.1 },
  { month: 'Jun', ventas: 184, pedidos: 12.4 },
  { month: 'Jul', ventas: 196, pedidos: 13.1 },
  { month: 'Ago', ventas: 178, pedidos: 11.8 },
];

export const clientsChart = [
  { month: 'Ene', nuevos: 320, activos: 38200 },
  { month: 'Feb', nuevos: 410, activos: 38610 },
  { month: 'Mar', nuevos: 380, activos: 38990 },
  { month: 'Abr', nuevos: 520, activos: 39510 },
  { month: 'May', nuevos: 480, activos: 39990 },
  { month: 'Jun', nuevos: 610, activos: 40600 },
  { month: 'Jul', nuevos: 560, activos: 41160 },
  { month: 'Ago', nuevos: 690, activos: 41850 },
];

export const activity: ActivityItem[] = [
  {
    id: 'a1',
    type: 'order',
    title: 'Nuevo pedido #FF-3421',
    description: 'Farmacia Central · € 128,40 · 3 artículos',
    time: 'Hace 4 min',
  },
  {
    id: 'a2',
    type: 'pharmacy',
    title: 'Farmacia Sagrado Corazón se ha registrado',
    description: 'Plan Pro · Sevilla · en periodo de prueba',
    time: 'Hace 22 min',
  },
  {
    id: 'a3',
    type: 'payment',
    title: 'Pago recibido · € 249,00',
    description: 'Farmacia Nuestra Señora · Plan Business anual',
    time: 'Hace 1 h',
  },
  {
    id: 'a4',
    type: 'client',
    title: '142 nuevos clientes importados',
    description: 'Farmacia Llopis · importación Excel completada',
    time: 'Hace 2 h',
  },
  {
    id: 'a5',
    type: 'alert',
    title: 'Stock bajo en 18 productos',
    description: 'Farmacia Mediterránea · requiere reposición',
    time: 'Hace 3 h',
  },
  {
    id: 'a6',
    type: 'order',
    title: 'Pedido #FF-3398 marcado como entregado',
    description: 'Farmacia Salut · entregado al cliente',
    time: 'Hace 5 h',
  },
];

const provinces = [
  'Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Alicante', 'Málaga', 'Zaragoza',
];

function buildUsers(adminName: string, adminEmail: string, adminPhone: string): PharmacyUser[] {
  return [
    {
      id: 'u1',
      name: adminName,
      email: adminEmail,
      role: 'admin',
      status: 'active',
      lastAccess: '2025-07-30T07:42:00Z',
    },
    {
      id: 'u2',
      name: 'Laura Fernández',
      email: 'laura@farmacia.es',
      role: 'employee',
      status: 'active',
      lastAccess: '2025-07-29T18:20:00Z',
    },
    {
      id: 'u3',
      name: 'Carlos Nieto',
      email: 'carlos@farmacia.es',
      role: 'employee',
      status: 'invited',
      lastAccess: null,
    },
  ];
}

function buildActivity(): PharmacyActivityItem[] {
  return [
    {
      id: 'pa1',
      type: 'order',
      title: 'Pedido recibido #FF-3421',
      description: 'Cliente: Marta Rivas · € 128,40 · 3 artículos',
      time: 'Hace 4 min',
      user: 'Sistema',
    },
    {
      id: 'pa2',
      type: 'user',
      title: 'Usuario creado',
      description: 'Carlos Nieto añadido como empleado',
      time: 'Hace 2 h',
      user: 'Marta Rivas',
    },
    {
      id: 'pa3',
      type: 'qr',
      title: 'QR regenerado',
      description: 'Se ha generado un nuevo código QR para la farmacia',
      time: 'Hace 1 día',
      user: 'Marta Rivas',
    },
    {
      id: 'pa4',
      type: 'logo',
      title: 'Logo actualizado',
      description: 'Se ha actualizado el logotipo de la farmacia',
      time: 'Hace 3 días',
      user: 'Marta Rivas',
    },
    {
      id: 'pa5',
      type: 'contract',
      title: 'Contrato enviado',
      description: 'Versión v2.1 enviada para firma digital',
      time: 'Hace 1 semana',
      user: 'Admin FarmaFácil',
    },
    {
      id: 'pa6',
      type: 'payment',
      title: 'Pago procesado',
      description: 'Plan Business · € 249,00 · pago mensual',
      time: 'Hace 2 semanas',
      user: 'Sistema',
    },
  ];
}

export const pharmacies: Pharmacy[] = [
  {
    id: 'ph1',
    name: 'Farmacia Central',
    legalName: 'Farmacia Central S.L.',
    cif: 'B-12345678',
    address: 'Calle Gran Vía 42',
    postalCode: '28013',
    city: 'Madrid',
    province: 'Madrid',
    email: 'contacto@farmaciacentral.es',
    phone: '+34 911 23 45 67',
    web: 'www.farmaciacentral.es',
    status: 'active',
    plan: 'business',
    clients: 1840,
    products: 1240,
    orders: 320,
    monthlyRevenue: 4820,
    joinedAt: '2024-02-14',
    logoColor: '#2EC4C7',
    adminUser: {
      name: 'Marta Rivas',
      email: 'marta@farmaciacentral.es',
      phone: '+34 611 22 33 44',
    },
    contract: {
      status: 'signed',
      version: 'v2.1',
      sentAt: '2024-02-10',
      signedAt: '2024-02-14',
      renewalAt: '2026-02-14',
    },
    qr: {
      url: 'https://farmafacil.app/p/farmacia-central',
      code: 'FF-PH1-7K2X9',
    },
    customization: {
      primaryColor: '#2EC4C7',
      secondaryColor: '#0EA5E9',
      welcomeMessage: '¡Bienvenido a Farmacia Central! Tu salud es nuestra prioridad.',
      schedule: 'L-V 9:00-21:30 · S 9:30-14:00',
      whatsapp: '+34 611 22 33 44',
    },
    users: buildUsers('Marta Rivas', 'marta@farmaciacentral.es', '+34 611 22 33 44'),
    activity: buildActivity(),
  },
  {
    id: 'ph2',
    name: 'Farmacia Llopis',
    legalName: 'Farmacia Llopis S.L.',
    cif: 'B-87654321',
    address: 'Avinguda del Nord 15',
    postalCode: '46001',
    city: 'Valencia',
    province: 'Valencia',
    email: 'info@farmaciallopis.es',
    phone: '+34 962 11 22 33',
    web: 'www.farmaciallopis.es',
    status: 'active',
    plan: 'pro',
    clients: 980,
    products: 620,
    orders: 142,
    monthlyRevenue: 1980,
    joinedAt: '2024-04-03',
    logoColor: '#6366F1',
    adminUser: {
      name: 'Javier Llopis',
      email: 'javier@farmaciallopis.es',
      phone: '+34 622 33 44 55',
    },
    contract: {
      status: 'signed',
      version: 'v1.4',
      sentAt: '2024-03-28',
      signedAt: '2024-04-03',
      renewalAt: '2025-04-03',
    },
    qr: {
      url: 'https://farmafacil.app/p/farmacia-llopis',
      code: 'FF-PH2-3M8Z1',
    },
    customization: {
      primaryColor: '#6366F1',
      secondaryColor: '#8B5CF6',
      welcomeMessage: 'Farmacia Llopis, cuidando de ti desde 1985.',
      schedule: 'L-V 9:00-20:00 · S 10:00-14:00',
      whatsapp: '+34 622 33 44 55',
    },
    users: buildUsers('Javier Llopis', 'javier@farmaciallopis.es', '+34 622 33 44 55'),
    activity: buildActivity(),
  },
  {
    id: 'ph3',
    name: 'Farmacia Mediterránea',
    legalName: 'Farmacia Mediterránea S.L.',
    cif: 'B-11223344',
    address: 'Carrer Alacant 8',
    postalCode: '03002',
    city: 'Alicante',
    province: 'Alicante',
    email: 'hola@farmaciamediterranea.es',
    phone: '+34 965 44 55 66',
    web: 'www.farmaciamediterranea.es',
    status: 'pending_setup',
    plan: 'starter',
    clients: 410,
    products: 280,
    orders: 58,
    monthlyRevenue: 0,
    joinedAt: '2025-01-20',
    logoColor: '#F59E0B',
    adminUser: {
      name: 'Lucía Marín',
      email: 'lucia@farmacamed.es',
      phone: '+34 633 44 55 66',
    },
    contract: {
      status: 'signed',
      version: 'v1.0',
      sentAt: '2025-01-15',
      signedAt: '2025-01-20',
      renewalAt: '2026-01-20',
    },
    qr: {
      url: 'https://farmafacil.app/p/farmacia-mediterranea',
      code: 'FF-PH3-9Q4L7',
    },
    customization: {
      primaryColor: '#F59E0B',
      secondaryColor: '#F97316',
      welcomeMessage: 'Farmacia Mediterránea, tu farmacia de confianza.',
      schedule: 'L-V 9:00-21:00 · S 9:00-14:00',
      whatsapp: '+34 633 44 55 66',
    },
    users: buildUsers('Lucía Marín', 'lucia@farmacamed.es', '+34 633 44 55 66'),
    activity: buildActivity(),
  },
  {
    id: 'ph4',
    name: 'Farmacia Salut',
    legalName: 'Farmacia Salut S.L.',
    cif: 'B-55667788',
    address: 'Passeig de Gràcia 50',
    postalCode: '08007',
    city: 'Barcelona',
    province: 'Barcelona',
    email: 'contacto@farmaciasalut.es',
    phone: '+34 933 77 88 99',
    web: 'www.farmaciasalut.es',
    status: 'active',
    plan: 'enterprise',
    clients: 3210,
    products: 2840,
    orders: 612,
    monthlyRevenue: 9240,
    joinedAt: '2023-11-08',
    logoColor: '#22C55E',
    adminUser: {
      name: 'Pau Vidal',
      email: 'pau@farmaciasalut.es',
      phone: '+34 644 55 66 77',
    },
    contract: {
      status: 'signed',
      version: 'v3.0',
      sentAt: '2023-11-01',
      signedAt: '2023-11-08',
      renewalAt: '2026-11-08',
    },
    qr: {
      url: 'https://farmafacil.app/p/farmacia-salut',
      code: 'FF-PH4-1X6T3',
    },
    customization: {
      primaryColor: '#22C55E',
      secondaryColor: '#16A34A',
      welcomeMessage: 'Salut! La teva farmàpia de confiança.',
      schedule: 'L-D 8:00-22:00',
      whatsapp: '+34 644 55 66 77',
    },
    users: buildUsers('Pau Vidal', 'pau@farmaciasalut.es', '+34 644 55 66 77'),
    activity: buildActivity(),
  },
  {
    id: 'ph5',
    name: 'Farmacia Nuestra Señora',
    legalName: 'Farmacia Nuestra Señora S.L.',
    cif: 'B-99887766',
    address: 'Calle Feria 25',
    postalCode: '41002',
    city: 'Sevilla',
    province: 'Sevilla',
    email: 'info@farmaciansra.es',
    phone: '+34 954 10 20 30',
    web: 'www.farmaciansra.es',
    status: 'active',
    plan: 'business',
    clients: 1320,
    products: 890,
    orders: 210,
    monthlyRevenue: 3960,
    joinedAt: '2024-06-22',
    logoColor: '#EF4444',
    adminUser: {
      name: 'Carmen Ortega',
      email: 'carmen@farmaciansra.es',
      phone: '+34 655 66 77 88',
    },
    contract: {
      status: 'expiring',
      version: 'v2.0',
      sentAt: '2024-06-15',
      signedAt: '2024-06-22',
      renewalAt: '2025-08-22',
    },
    qr: {
      url: 'https://farmafacil.app/p/farmacia-nuestra-senora',
      code: 'FF-PH5-5R8W2',
    },
    customization: {
      primaryColor: '#EF4444',
      secondaryColor: '#F97316',
      welcomeMessage: 'Farmacia Nuestra Señora, a tu servicio.',
      schedule: 'L-V 9:00-21:30 · S 9:30-14:00',
      whatsapp: '+34 655 66 77 88',
    },
    users: buildUsers('Carmen Ortega', 'carmen@farmaciansra.es', '+34 655 66 77 88'),
    activity: buildActivity(),
  },
  {
    id: 'ph6',
    name: 'Farmacia Sagrado Corazón',
    legalName: 'Farmacia Sagrado Corazón S.L.',
    cif: 'B-44332211',
    address: 'Calle Sierpes 12',
    postalCode: '41004',
    city: 'Sevilla',
    province: 'Sevilla',
    email: 'contacto@farmaciasagradoc.es',
    phone: '+34 954 33 44 55',
    web: '',
    status: 'contract_sent',
    plan: 'pro',
    clients: 0,
    products: 0,
    orders: 0,
    monthlyRevenue: 0,
    joinedAt: '2025-07-28',
    logoColor: '#8B5CF6',
    adminUser: {
      name: 'Antonio Reyes',
      email: 'antonio@farmasagrado.es',
      phone: '+34 666 77 88 99',
    },
    contract: {
      status: 'sent',
      version: 'v1.0',
      sentAt: '2025-07-28',
      signedAt: null,
      renewalAt: null,
    },
    qr: {
      url: 'https://farmafacil.app/p/farmacia-sagrado-corazon',
      code: 'FF-PH6-2K9P4',
    },
    customization: {
      primaryColor: '#8B5CF6',
      secondaryColor: '#6366F1',
      welcomeMessage: 'Farmacia Sagrado Corazón.',
      schedule: 'L-V 9:00-21:00',
      whatsapp: '+34 666 77 88 99',
    },
    users: buildUsers('Antonio Reyes', 'antonio@farmasagrado.es', '+34 666 77 88 99'),
    activity: buildActivity(),
  },
  {
    id: 'ph7',
    name: 'Farmacia del Puerto',
    legalName: 'Farmacia del Puerto S.L.',
    cif: 'B-77889900',
    address: 'Paseo Marítimo 4',
    postalCode: '29016',
    city: 'Málaga',
    province: 'Málaga',
    email: 'info@farmaciapuerto.es',
    phone: '+34 952 66 77 88',
    web: 'www.farmaciapuerto.es',
    status: 'suspended',
    plan: 'starter',
    clients: 240,
    products: 180,
    orders: 12,
    monthlyRevenue: 0,
    joinedAt: '2024-09-15',
    logoColor: '#0EA5E9',
    adminUser: {
      name: 'Rocío Belmonte',
      email: 'rocio@farmaciapuerto.es',
      phone: '+34 677 88 99 00',
    },
    contract: {
      status: 'expired',
      version: 'v1.2',
      sentAt: '2024-09-10',
      signedAt: '2024-09-15',
      renewalAt: '2025-03-15',
    },
    qr: {
      url: 'https://farmafacil.app/p/farmacia-del-puerto',
      code: 'FF-PH7-8T3N6',
    },
    customization: {
      primaryColor: '#0EA5E9',
      secondaryColor: '#0284C7',
      welcomeMessage: 'Farmacia del Puerto, junto al mar.',
      schedule: 'L-V 9:00-20:00',
      whatsapp: '+34 677 88 99 00',
    },
    users: buildUsers('Rocío Belmonte', 'rocio@farmaciapuerto.es', '+34 677 88 99 00'),
    activity: buildActivity(),
  },
  {
    id: 'ph8',
    name: 'Farmacia Goya',
    legalName: 'Farmacia Goya S.L.',
    cif: 'B-66554433',
    address: 'Calle Don Jaime I 30',
    postalCode: '50003',
    city: 'Zaragoza',
    province: 'Zaragoza',
    email: 'contacto@farmaciagoya.es',
    phone: '+34 976 12 34 56',
    web: 'www.farmaciagoya.es',
    status: 'active',
    plan: 'pro',
    clients: 760,
    products: 510,
    orders: 98,
    monthlyRevenue: 1490,
    joinedAt: '2024-12-01',
    logoColor: '#EC4899',
    adminUser: {
      name: 'Santiago Goya',
      email: 'santiago@farmaciagoya.es',
      phone: '+34 688 99 00 11',
    },
    contract: {
      status: 'signed',
      version: 'v1.3',
      sentAt: '2024-11-25',
      signedAt: '2024-12-01',
      renewalAt: '2025-12-01',
    },
    qr: {
      url: 'https://farmafacil.app/p/farmacia-goya',
      code: 'FF-PH8-4M7Q1',
    },
    customization: {
      primaryColor: '#EC4899',
      secondaryColor: '#F472B6',
      welcomeMessage: 'Farmacia Goya, tradición y salud.',
      schedule: 'L-V 9:00-21:30 · S 10:00-14:00',
      whatsapp: '+34 688 99 00 11',
    },
    users: buildUsers('Santiago Goya', 'santiago@farmaciagoya.es', '+34 688 99 00 11'),
    activity: buildActivity(),
  },
];

export const recentOrders: Order[] = [
  {
    id: 'o1',
    code: 'FF-3421',
    clientName: 'Marta Rivas',
    pharmacyId: 'ph1',
    pharmacyName: 'Farmacia Central',
    status: 'pending',
    total: 128.4,
    items: 3,
    createdAt: '2025-07-30T08:14:00Z',
  },
  {
    id: 'o2',
    code: 'FF-3420',
    clientName: 'Pau Vidal',
    pharmacyId: 'ph4',
    pharmacyName: 'Farmacia Salut',
    status: 'preparing',
    total: 64.9,
    items: 2,
    createdAt: '2025-07-30T07:52:00Z',
  },
  {
    id: 'o3',
    code: 'FF-3419',
    clientName: 'Lucía Marín',
    pharmacyId: 'ph3',
    pharmacyName: 'Farmacia Mediterránea',
    status: 'prepared',
    total: 212.0,
    items: 7,
    createdAt: '2025-07-30T07:30:00Z',
  },
  {
    id: 'o4',
    code: 'FF-3418',
    clientName: 'Javier Llopis',
    pharmacyId: 'ph2',
    pharmacyName: 'Farmacia Llopis',
    status: 'delivered',
    total: 38.5,
    items: 1,
    createdAt: '2025-07-29T19:10:00Z',
  },
  {
    id: 'o5',
    code: 'FF-3417',
    clientName: 'Carmen Ortega',
    pharmacyId: 'ph5',
    pharmacyName: 'Farmacia Nuestra Señora',
    status: 'cancelled',
    total: 89.0,
    items: 4,
    createdAt: '2025-07-29T16:42:00Z',
  },
];

export const clients: Client[] = [
  {
    id: 'c1',
    name: 'Marta Rivas',
    email: 'marta.rivas@example.com',
    phone: '+34 611 22 33 44',
    pharmacyId: 'ph1',
    pharmacyName: 'Farmacia Central',
    orders: 42,
    totalSpent: 1280.5,
    lastOrderAt: '2025-07-30T08:14:00Z',
    status: 'active',
    tags: ['VIP', 'Crónico'],
  },
  {
    id: 'c2',
    name: 'Pau Vidal',
    email: 'pau.vidal@example.com',
    phone: '+34 622 33 44 55',
    pharmacyId: 'ph4',
    pharmacyName: 'Farmacia Salut',
    orders: 88,
    totalSpent: 3120.0,
    lastOrderAt: '2025-07-30T07:52:00Z',
    status: 'active',
    tags: ['VIP'],
  },
  {
    id: 'c3',
    name: 'Lucía Marín',
    email: 'lucia.marin@example.com',
    phone: '+34 633 44 55 66',
    pharmacyId: 'ph3',
    pharmacyName: 'Farmacia Mediterránea',
    orders: 12,
    totalSpent: 410.2,
    lastOrderAt: '2025-07-30T07:30:00Z',
    status: 'active',
    tags: [],
  },
  {
    id: 'c4',
    name: 'Javier Llopis',
    email: 'javier.llopis@example.com',
    phone: '+34 644 55 66 77',
    pharmacyId: 'ph2',
    pharmacyName: 'Farmacia Llopis',
    orders: 5,
    totalSpent: 96.5,
    lastOrderAt: '2025-07-29T19:10:00Z',
    status: 'inactive',
    tags: ['Nuevo'],
  },
  {
    id: 'c5',
    name: 'Carmen Ortega',
    email: 'carmen.ortega@example.com',
    phone: '+34 655 66 77 88',
    pharmacyId: 'ph5',
    pharmacyName: 'Farmacia Nuestra Señora',
    orders: 27,
    totalSpent: 842.0,
    lastOrderAt: '2025-07-29T16:42:00Z',
    status: 'active',
    tags: ['Crónico'],
  },
];

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Paracetamol 1g · 40 comprimidos',
    sku: 'MED-PARA-1G',
    category: 'Analgésicos',
    price: 4.2,
    stock: 1240,
    pharmacyId: 'ph1',
    featured: true,
    status: 'in_stock',
  },
  {
    id: 'p2',
    name: 'Ibuprofeno 600mg · 30 cápsulas',
    sku: 'MED-IBU-600',
    category: 'Antiinflamatorios',
    price: 5.1,
    stock: 32,
    pharmacyId: 'ph1',
    featured: false,
    status: 'low_stock',
  },
  {
    id: 'p3',
    name: 'Vitamina C 1g · 20 efervescentes',
    sku: 'SUP-VITC-1G',
    category: 'Vitaminas',
    price: 6.9,
    stock: 0,
    pharmacyId: 'ph2',
    featured: true,
    status: 'out_of_stock',
  },
  {
    id: 'p4',
    name: 'Gel hidroalcohólico 500ml',
    sku: 'HIG-GEL-500',
    category: 'Higiene',
    price: 3.4,
    stock: 580,
    pharmacyId: 'ph4',
    featured: false,
    status: 'in_stock',
  },
  {
    id: 'p5',
    name: 'Mascarillas FFP2 · 10 uds',
    sku: 'HIG-MASK-FFP2',
    category: 'Higiene',
    price: 8.9,
    stock: 14,
    pharmacyId: 'ph5',
    featured: true,
    status: 'low_stock',
  },
];

export const pharmacyProducts: Product[] = [
  {
    id: 'pp1',
    name: 'Paracetamol 1g · 40 comprimidos',
    sku: 'MED-PARA-1G',
    category: 'Analgésicos',
    price: 4.2,
    stock: 1240,
    pharmacyId: 'ph1',
    featured: true,
    status: 'in_stock',
  },
  {
    id: 'pp2',
    name: 'Ibuprofeno 600mg · 30 cápsulas',
    sku: 'MED-IBU-600',
    category: 'Antiinflamatorios',
    price: 5.1,
    stock: 32,
    pharmacyId: 'ph1',
    featured: false,
    status: 'low_stock',
  },
  {
    id: 'pp3',
    name: 'Amoxicilina 500mg · 20 cápsulas',
    sku: 'MED-AMOX-500',
    category: 'Antibióticos',
    price: 7.8,
    stock: 410,
    pharmacyId: 'ph1',
    featured: false,
    status: 'in_stock',
  },
  {
    id: 'pp4',
    name: 'Vitamina D3 1000UI · 30 cápsulas',
    sku: 'SUP-VITD-1K',
    category: 'Vitaminas',
    price: 9.5,
    stock: 0,
    pharmacyId: 'ph1',
    featured: true,
    status: 'out_of_stock',
  },
  {
    id: 'pp5',
    name: 'Gel hidroalcohólico 500ml',
    sku: 'HIG-GEL-500',
    category: 'Higiene',
    price: 3.4,
    stock: 580,
    pharmacyId: 'ph1',
    featured: false,
    status: 'in_stock',
  },
  {
    id: 'pp6',
    name: 'Mascarillas FFP2 · 10 uds',
    sku: 'HIG-MASK-FFP2',
    category: 'Higiene',
    price: 8.9,
    stock: 14,
    pharmacyId: 'ph1',
    featured: true,
    status: 'low_stock',
  },
  {
    id: 'pp7',
    name: 'Tiras reactivas glucosa · 50 uds',
    sku: 'DIA-STRIP-50',
    category: 'Diabetes',
    price: 18.9,
    stock: 220,
    pharmacyId: 'ph1',
    featured: false,
    status: 'in_stock',
  },
];

export const pharmacyOrders: Order[] = [
  {
    id: 'po1',
    code: 'FF-3421',
    clientName: 'Marta Rivas',
    pharmacyId: 'ph1',
    pharmacyName: 'Farmacia Central',
    status: 'pending',
    total: 128.4,
    items: 3,
    createdAt: '2025-07-30T08:14:00Z',
  },
  {
    id: 'po2',
    code: 'FF-3415',
    clientName: 'Roberto Asensio',
    pharmacyId: 'ph1',
    pharmacyName: 'Farmacia Central',
    status: 'preparing',
    total: 64.9,
    items: 2,
    createdAt: '2025-07-30T07:02:00Z',
  },
  {
    id: 'po3',
    code: 'FF-3408',
    clientName: 'Elena Castillo',
    pharmacyId: 'ph1',
    pharmacyName: 'Farmacia Central',
    status: 'prepared',
    total: 212.0,
    items: 7,
    createdAt: '2025-07-29T18:30:00Z',
  },
  {
    id: 'po4',
    code: 'FF-3392',
    clientName: 'Manuel Vega',
    pharmacyId: 'ph1',
    pharmacyName: 'Farmacia Central',
    status: 'delivered',
    total: 38.5,
    items: 1,
    createdAt: '2025-07-29T14:10:00Z',
  },
  {
    id: 'po5',
    code: 'FF-3388',
    clientName: 'Sara Jiménez',
    pharmacyId: 'ph1',
    pharmacyName: 'Farmacia Central',
    status: 'delivered',
    total: 156.2,
    items: 5,
    createdAt: '2025-07-28T11:22:00Z',
  },
  {
    id: 'po6',
    code: 'FF-3371',
    clientName: 'David Ruiz',
    pharmacyId: 'ph1',
    pharmacyName: 'Farmacia Central',
    status: 'cancelled',
    total: 89.0,
    items: 4,
    createdAt: '2025-07-28T09:42:00Z',
  },
];

export const planLabels: Record<string, string> = {
  starter: 'Starter',
  pro: 'Pro',
  business: 'Business',
  enterprise: 'Enterprise',
};

export const statusLabels: Record<string, string> = {
  draft: 'Borrador',
  pending_contract: 'Pendiente contrato',
  contract_sent: 'Contrato enviado',
  contract_signed: 'Contrato firmado',
  pending_setup: 'Pendiente configuración',
  active: 'Activa',
  suspended: 'Suspendida',
};

export const contractStatusLabels: Record<string, string> = {
  none: 'Sin contrato',
  draft: 'Borrador',
  sent: 'Enviado',
  signed: 'Firmado',
  expiring: 'Próximo a renovar',
  expired: 'Expirado',
};

export const orderStatusLabels: Record<string, string> = {
  pending: 'Pendiente',
  preparing: 'Preparación',
  prepared: 'Preparado',
  delivered: 'Entregado',
  cancelled: 'Cancelado',
};

export const userRoleLabels: Record<string, string> = {
  superadmin: 'SuperAdministrador',
  pharmacy_admin: 'Administrador Farmacia',
  employee: 'Empleado',
  client: 'Cliente',
  admin: 'Administrador',
};

export const userStatusLabels: Record<string, string> = {
  active: 'Activo',
  pending: 'Pendiente',
  suspended: 'Suspendido',
  invite_sent: 'Invitación enviada',
  invite_accepted: 'Invitación aceptada',
  invited: 'Invitado',
  disabled: 'Desactivado',
};

export const productStatusLabels: Record<string, string> = {
  in_stock: 'En stock',
  low_stock: 'Stock bajo',
  out_of_stock: 'Sin stock',
};

export const productCategories = [
  'Analgésicos',
  'Antiinflamatorios',
  'Antibióticos',
  'Vitaminas',
  'Higiene',
  'Diabetes',
  'Dermatología',
  'Cuidado infantil',
];

/* ------------------------------------------------------------------ */
/*  User management mock data                                        */
/* ------------------------------------------------------------------ */

import type { UserAccount, PermissionGroup } from './types';

function buildUserActivity(): UserAccount['activity'] {
  return [
    {
      id: 'ua1',
      type: 'login',
      title: 'Inicio de sesión',
      description: 'Acceso desde Madrid, España',
      time: 'Hace 4 min',
    },
    {
      id: 'ua2',
      type: 'update',
      title: 'Perfil actualizado',
      description: 'Se modificó el número de teléfono',
      time: 'Hace 2 h',
    },
    {
      id: 'ua3',
      type: 'create',
      title: 'Pedido creado #FF-3421',
      description: 'Nuevo pedido para Marta Rivas',
      time: 'Hace 5 h',
    },
    {
      id: 'ua4',
      type: 'config',
      title: 'Configuración de farmacia',
      description: 'Se actualizó el horario de atención',
      time: 'Hace 1 día',
    },
    {
      id: 'ua5',
      type: 'login',
      title: 'Inicio de sesión',
      description: 'Acceso desde la app móvil',
      time: 'Hace 2 días',
    },
  ];
}

export const users: UserAccount[] = [
  {
    id: 'u1',
    name: 'Admin FarmaFácil',
    email: 'admin@farmafacil.es',
    phone: '+34 600 00 00 00',
    role: 'superadmin',
    pharmacyId: null,
    pharmacyName: null,
    status: 'active',
    lastAccess: '2025-07-30T08:00:00Z',
    createdAt: '2023-01-01',
    avatarColor: '#2EC4C7',
    activity: buildUserActivity(),
    permissions: {
      dashboard_view: true,
      pharmacies_manage: true,
      clients_manage: true,
      catalog_manage: true,
      orders_manage: true,
      users_manage: true,
      settings_manage: true,
    },
  },
  {
    id: 'u2',
    name: 'Marta Rivas',
    email: 'marta@farmaciacentral.es',
    phone: '+34 611 22 33 44',
    role: 'pharmacy_admin',
    pharmacyId: 'ph1',
    pharmacyName: 'Farmacia Central',
    status: 'active',
    lastAccess: '2025-07-30T07:42:00Z',
    createdAt: '2024-02-14',
    avatarColor: '#2EC4C7',
    activity: buildUserActivity(),
    permissions: {
      dashboard_view: true,
      pharmacies_manage: false,
      clients_manage: true,
      catalog_manage: true,
      orders_manage: true,
      users_manage: true,
      settings_manage: true,
    },
  },
  {
    id: 'u3',
    name: 'Javier Llopis',
    email: 'javier@farmaciallopis.es',
    phone: '+34 622 33 44 55',
    role: 'pharmacy_admin',
    pharmacyId: 'ph2',
    pharmacyName: 'Farmacia Llopis',
    status: 'active',
    lastAccess: '2025-07-29T18:20:00Z',
    createdAt: '2024-04-03',
    avatarColor: '#6366F1',
    activity: buildUserActivity(),
    permissions: {
      dashboard_view: true,
      pharmacies_manage: false,
      clients_manage: true,
      catalog_manage: true,
      orders_manage: true,
      users_manage: true,
      settings_manage: true,
    },
  },
  {
    id: 'u4',
    name: 'Laura Fernández',
    email: 'laura@farmaciacentral.es',
    phone: '+34 633 44 55 66',
    role: 'employee',
    pharmacyId: 'ph1',
    pharmacyName: 'Farmacia Central',
    status: 'active',
    lastAccess: '2025-07-29T16:10:00Z',
    createdAt: '2024-03-20',
    avatarColor: '#F59E0B',
    activity: buildUserActivity(),
    permissions: {
      dashboard_view: true,
      pharmacies_manage: false,
      clients_manage: true,
      catalog_manage: true,
      orders_manage: true,
      users_manage: false,
      settings_manage: false,
    },
  },
  {
    id: 'u5',
    name: 'Carlos Nieto',
    email: 'carlos@farmaciacentral.es',
    phone: '+34 644 55 66 77',
    role: 'employee',
    pharmacyId: 'ph1',
    pharmacyName: 'Farmacia Central',
    status: 'invite_sent',
    lastAccess: null,
    createdAt: '2025-07-28',
    avatarColor: '#8B5CF6',
    activity: [],
    permissions: {
      dashboard_view: true,
      pharmacies_manage: false,
      clients_manage: true,
      catalog_manage: false,
      orders_manage: true,
      users_manage: false,
      settings_manage: false,
    },
  },
  {
    id: 'u6',
    name: 'Pau Vidal',
    email: 'pau@farmaciasalut.es',
    phone: '+34 644 55 66 77',
    role: 'pharmacy_admin',
    pharmacyId: 'ph4',
    pharmacyName: 'Farmacia Salut',
    status: 'active',
    lastAccess: '2025-07-30T07:52:00Z',
    createdAt: '2023-11-08',
    avatarColor: '#22C55E',
    activity: buildUserActivity(),
    permissions: {
      dashboard_view: true,
      pharmacies_manage: false,
      clients_manage: true,
      catalog_manage: true,
      orders_manage: true,
      users_manage: true,
      settings_manage: true,
    },
  },
  {
    id: 'u7',
    name: 'Carmen Ortega',
    email: 'carmen@farmaciansra.es',
    phone: '+34 655 66 77 88',
    role: 'pharmacy_admin',
    pharmacyId: 'ph5',
    pharmacyName: 'Farmacia Nuestra Señora',
    status: 'pending',
    lastAccess: null,
    createdAt: '2024-06-22',
    avatarColor: '#EF4444',
    activity: buildUserActivity(),
    permissions: {
      dashboard_view: true,
      pharmacies_manage: false,
      clients_manage: true,
      catalog_manage: true,
      orders_manage: true,
      users_manage: true,
      settings_manage: true,
    },
  },
  {
    id: 'u8',
    name: 'Rocío Belmonte',
    email: 'rocio@farmaciapuerto.es',
    phone: '+34 677 88 99 00',
    role: 'pharmacy_admin',
    pharmacyId: 'ph7',
    pharmacyName: 'Farmacia del Puerto',
    status: 'suspended',
    lastAccess: '2025-03-15T10:00:00Z',
    createdAt: '2024-09-15',
    avatarColor: '#0EA5E9',
    activity: buildUserActivity(),
    permissions: {
      dashboard_view: false,
      pharmacies_manage: false,
      clients_manage: false,
      catalog_manage: false,
      orders_manage: false,
      users_manage: false,
      settings_manage: false,
    },
  },
  {
    id: 'u9',
    name: 'Santiago Goya',
    email: 'santiago@farmaciagoya.es',
    phone: '+34 688 99 00 11',
    role: 'pharmacy_admin',
    pharmacyId: 'ph8',
    pharmacyName: 'Farmacia Goya',
    status: 'invite_accepted',
    lastAccess: '2025-07-28T14:00:00Z',
    createdAt: '2024-12-01',
    avatarColor: '#EC4899',
    activity: buildUserActivity(),
    permissions: {
      dashboard_view: true,
      pharmacies_manage: false,
      clients_manage: true,
      catalog_manage: true,
      orders_manage: true,
      users_manage: true,
      settings_manage: true,
    },
  },
  {
    id: 'u10',
    name: 'Lucía Marín',
    email: 'lucia@farmacamed.es',
    phone: '+34 633 44 55 66',
    role: 'employee',
    pharmacyId: 'ph3',
    pharmacyName: 'Farmacia Mediterránea',
    status: 'active',
    lastAccess: '2025-07-30T07:30:00Z',
    createdAt: '2025-01-20',
    avatarColor: '#F59E0B',
    activity: buildUserActivity(),
    permissions: {
      dashboard_view: true,
      pharmacies_manage: false,
      clients_manage: true,
      catalog_manage: true,
      orders_manage: true,
      users_manage: false,
      settings_manage: false,
    },
  },
];

export const permissionGroups: PermissionGroup[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    description: 'Acceso al panel principal y métricas',
    permissions: [
      { id: 'dashboard_view', label: 'Ver dashboard', description: 'Acceso al panel de control' },
    ],
  },
  {
    id: 'pharmacies',
    label: 'Farmacias',
    description: 'Gestión de farmacias de la red',
    permissions: [
      { id: 'pharmacies_view', label: 'Ver farmacias', description: 'Listar y consultar farmacias' },
      { id: 'pharmacies_manage', label: 'Gestionar farmacias', description: 'Crear, editar y suspender farmacias' },
    ],
  },
  {
    id: 'clients',
    label: 'Clientes',
    description: 'Gestión de la base de clientes',
    permissions: [
      { id: 'clients_view', label: 'Ver clientes', description: 'Listar y consultar clientes' },
      { id: 'clients_manage', label: 'Gestionar clientes', description: 'Crear, editar y importar clientes' },
    ],
  },
  {
    id: 'catalog',
    label: 'Catálogo',
    description: 'Gestión de productos y stock',
    permissions: [
      { id: 'catalog_view', label: 'Ver catálogo', description: 'Listar y consultar productos' },
      { id: 'catalog_manage', label: 'Gestionar catálogo', description: 'Crear, editar y importar productos' },
    ],
  },
  {
    id: 'orders',
    label: 'Pedidos',
    description: 'Gestión de pedidos y estados',
    permissions: [
      { id: 'orders_view', label: 'Ver pedidos', description: 'Listar y consultar pedidos' },
      { id: 'orders_manage', label: 'Gestionar pedidos', description: 'Crear y cambiar estado de pedidos' },
    ],
  },
  {
    id: 'users',
    label: 'Usuarios',
    description: 'Gestión de usuarios y permisos',
    permissions: [
      { id: 'users_view', label: 'Ver usuarios', description: 'Listar y consultar usuarios' },
      { id: 'users_manage', label: 'Gestionar usuarios', description: 'Crear, editar y suspender usuarios' },
    ],
  },
  {
    id: 'settings',
    label: 'Configuración',
    description: 'Ajustes de la cuenta y la plataforma',
    permissions: [
      { id: 'settings_view', label: 'Ver configuración', description: 'Acceso a la configuración' },
      { id: 'settings_manage', label: 'Gestionar configuración', description: 'Modificar ajustes de la plataforma' },
    ],
  },
];
